AspNetMvcCRUD/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AspNetMvcCRUD.Models
{
    [Table("Produto")]
    public class Produto
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Preencha o Produto")]
        [Display(Name = "Produto")]
        [MaxLength(100)]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Preencha o Preço")]
        [Display(Name = "Preço")]
        public decimal Preco { get; set; }

        [Required(ErrorMessage = "Preencha a data de cadastro")]
        [Display(Name = "Data de Cadastro")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DataCadastro { get; set; } = DateTime.Today;

        public bool Ativo { get; set; } = true;

        [Required]
        [ForeignKey("Categoria")]
        public int CategoriaId { get; set; }

        public virtual Categoria Categoria { get; set; }

    }
}

AspNetMvcCRUD/Controllers/ProdutosController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AspNetMvcCRUD.Models;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Collections.Generic;

namespace AspNetMvcCRUD.Controllers
{
    public class ProdutosController : Controller
    {
        //private LojaContext db = new LojaContext();
        HttpClient client = new HttpClient();

        public ProdutosController()
        {

            client.BaseAddress = new Uri("http://localhost:50089/api/produtos");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }


        // GET: Produtos
        public ActionResult Index(string busca = null)
        {
            HttpResponseMessage response = client.GetAsync("/api/produtos").Result;
            List<Produto> produtos = new List<Produto>();

            if (response.IsSuccessStatusCode)
            {
                produtos = response.Content.ReadAsAsync<List<Produto>>().Result;
            }

            if (busca != null)
                return View(produtos.Where(a => a.Nome.ToUpper().Contains(busca.ToUpper())).ToList());
            return View(produtos.ToList());

        }




        // GET: Produtos/Details/5
        public ActionResult Details(int? id)
        {
            HttpResponseMessage response = client.GetAsync($"/api/produtos/{id}").Result;
            Produto produto = response.Content.ReadAsAsync<Produto>().Result;

            if (produto != null)

                return View(produto);
            else
                return HttpNotFound();

        }


        // GET: Produtos/Create
        public ActionResult Create()
        {
            HttpResponseMessage response = client.GetAsync("/api/categorias").Result;
            List<Categoria> categorias = new List<Categoria>();

            if (response.IsSuccessStatusCode)
            {
                categorias = response.Content.ReadAsAsync<List<Categoria>>().Result;
            }

            ViewBag.CategoriaId = new SelectList(categorias, "Id", "Nome");
            return View();
        }




        //// POST: Produtos/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Ativo,CategoriaId,DataCadastro,Nome,Preco")] Produto produto)
        {
            try
            {
                HttpResponseMessage response = client.PostAsJsonAsync<Produto>("/api/produtos", produto).Result;

                if (response.StatusCode == System.Net.HttpStatusCode.Created)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "Error na criação do produto.";
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }



        // GET: Produtos/Edit/5
        public ActionResult Edit(int? id)
        {
            HttpResponseMessage response = client.GetAsync($"/api/produtos/{id}").Result;
            Produto produto = response.Content.ReadAsAsync<Produto>().Result;

            HttpResponseMessage responses = client.GetAsync("/api/categorias").Result;
            List<Categoria> categorias = new List<Categoria>();

            if (produto != null)
            {
                if (responses.IsSuccessStatusCode)
                {
                    categorias = responses.Content.ReadAsAsync<List<Categoria>>().Result;
                    ViewBag.CategoriaId = new SelectList(categorias, "Id", "Nome", produto.CategoriaId);
                }
                return View(produto);
            }

            else
            { 
                return HttpNotFound();
            }

        }




        // PUT: Produtos/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Preco,DataCadastro,CategoriaId,Ativo")] int id, Produto produto)
        {
            try
            {
                HttpResponseMessage response = client.PutAsJsonAsync<Produto>($"/api/produtos/{id}", produto).Result;
                if (response.StatusCode == System.Net.HttpStatusCode.NoContent)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Error = "Error na alteração da produto.";
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }



        // GET: Produtos/Delete/5
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            HttpResponseMessage response = client.GetAsync($"/api/produtos/{id}").Result;

            Produto produto = response.Content.ReadAsAsync<Produto>().Result;

            if (produto != null)
                return View(produto);
            else
                return HttpNotFound();
        }


        // POST: Produtos/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                HttpResponseMessage response = client.DeleteAsync($"/api/produtos/{id}").Result;

                if (response.StatusCode != System.Net.HttpStatusCode.OK)
                    return RedirectToAction("Index");
                else
                {
                    ViewBag.Error = "Error ao deletar produto.";
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

    }
}

AspNetMvcCRUD/Views/Produtos/Create.cshtml
@model AspNetMvcCRUD.Models.Produto

@{
    ViewBag.Title = "Create";
}

<h2>Cadastro de Produto</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control", placeholder = "0,00", data_tipo = "moeda" } })
            @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataCadastro, "Data de Cadastro", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataCadastro, new { htmlAttributes = new { @class = "form-control", placeholder = "__/__/____", data_tipo = "data" } })
            @Html.ValidationMessageFor(model => model.DataCadastro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoriaId, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Ativo)
                @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

AspNetMvcCRUD/Views/Produtos/Delete.cshtml
@model AspNetMvcCRUD.Models.Produto

@{
    ViewBag.Title = "Delete";
}

    <h2>Deletar Produto</h2>

<h3>Tem certeza que deseja deletar este produto?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataCadastro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

AspNetMvcCRUD/Views/Produtos/Details.cshtml
@model AspNetMvcCRUD.Models.Produto

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes do Produto</h2>

<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DataCadastro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar", "Index")
</p>

AspNetMvcCRUD/Views/Produtos/Edit.cshtml
@model AspNetMvcCRUD.Models.Produto

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Produto</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control", placeholder = "0,00", data_tipo = "moeda" } })
            @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.DataCadastro, "Data de Cadastro", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataCadastro, new { htmlAttributes = new { @class = "form-control", placeholder = "__/__/____", data_tipo = "data" } })
            @Html.ValidationMessageFor(model => model.DataCadastro, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.CategoriaId, "Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Ativo)
                @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.mask.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/mascaras.js"></script>
    <script src="~/Scripts/validacao_ptbr.js"></script>
}

AspNetMvcCRUD/Views/Produtos/Index.cshtml
@model IEnumerable<AspNetMvcCRUD.Models.Produto>

@{
    ViewBag.Title = "Index";
}

<h2>Produtos</h2>
<h2></h2>

@using (Html.BeginForm("Index", "Produtos", FormMethod.Get, new { @class = "form-inline" }))
{
    <input type="text" placeholder="Consultar um produto" name="busca" class="form-control" />
    <input type="submit" class="btn btn-default" value="Consultar" />
}

<h2></h2>

<p>
    @Html.ActionLink("Criar Novo", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Ativo)
        </th>


        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataCadastro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoriaId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ativo)
            </td>

            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
                @Html.ActionLink("Deletar", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>